# Generated by Django 2.1.2 on 2018-10-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpaca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferredworkinghourperday',
            field=models.IntegerField(default=8),
        ),
    ]
